"""
This module consists of necessary configuration data used in other parts of the project.
"""
import os
import pandas as pd
from pathlib import Path
import warnings

def ignore_warnings():
    """
    Ignore warnings that are generated by the sklearn library.
    """
    warnings.filterwarnings("ignore")

# Static variable that contains the root directory of the project
ROOT_DIR = Path(__file__).parent.parent

def print_divider_line():
    # Prints a line consisting of 40 dashes
    print('-' * 40)